### ISSUE TITLE
500 errors on GET /saml/acs

### ISSUE THREAD

**Issue by tarjei** [hslavich/OneloginSamlBundle#112] opened 2020-02-14 10:29 UTC
Hi, we are getting 500 errors with this message:

` request.CRITICAL: Uncaught PHP Exception OneLogin\Saml2\Error: "SAML Response not found, Only supported HTTP_POST Binding" at /vendor/onelogin/php-saml/src/Saml2/Auth.php line 246`

This happens on a GET to `/saml/acs`.

I would love to know why this gets triggered, if someone has seen something like it.

Also, since OneLogin does not support GET requests to that endpoint, would it be ok to restrict the route to the POST method?

**Comment by JoostFaber** [comment] 2020-02-19 11:55
Hi there,

I used to have some trouble with this bundle but finally got a working example locally.
I have used this bundle as service provider (SP) with simplesaml-php as identity provider (IDP).

The /saml/acs route only supports POST as the error also describes. This is because (when configured correctly) the IDP will send POST request to this route containing the SAML response. A GET request wont have a SAML response since this bundle is only the SP side.

so to put things together:
1. the route saml/login will redirect you to the login of your IDP (in my case simplesaml-php)
2. if the login is succesfull the IDP will send a POST request to /saml/acs/ containing the SAML response.
3. if all validation checks at the SP side are OK, then the SAML-token will be created and the user is logged on.

**Comment by tarjei** [comment] 2020-02-19 14:26
Hi, yes I know the /saml/acs route only supports POST and it works. My problem is intermittent (maybe once every other day) requests of GET to /saml/acs which I suspect comes from a yet unknown errorpath. My problem is finding out why browsers are sending GET there.

Regards, 
Tarjei

**Comment by a-menshchikov** [comment] 2020-09-16 22:17
@tarjei hello!
Have you figured out with this error?

**Comment by tarjei** [comment] 2020-09-17 11:37
@a-menshchikov  no :) Have you seen it as well?

**Comment by a-menshchikov** [comment] 2020-09-17 14:02
@tarjei no :)

**Comment by a-menshchikov** [comment] 2022-03-28 08:46
I close this issue since could not reproduce the problem.
If it comes back, reopen this issue, please.

**Closed by a-menshchikov** 2022-03-28 08:46 UTC
